---
- name: change pw on initial login
  vars_files:
    - ../c_test/passwd.json
  hosts: "{{ hostname }}"
  gather_facts: false
  tasks:
  expect:
    command: sshpass -p {{ ansible_first_login_password }} ssh root@{{ host_ip }}
    timeout: 20
    responses:
      Password: "{{ ansible_first_login_password }}"
      UNIX password: "{{ ansible_first_login_password }}"
      New password: "{{ ansible_password }}"
      new password: "{{ ansible_password }}"
      "\\~\\]\\$": exit
  register: status
