---
- name: change pw on initial login
  vars_files:
    - ../c_test/passwd.json
  hosts: "{{ hostname }}"
  gather_facts: false
  tasks:
  - name: change passwd
    expect:
      command: ssh root@{{ host_ip }}
      timeout: 20
      responses:
        "Current password:": "{{ ansible_first_login_password }}"
        "New password:": "{{ ansible_password }}"
        "Retype new password:": "{{ ansible_password }}"
        "\\~\\]\\$": exit
    register: status
