---
- name: change pw on initial login
  vars_files:
    - ../vars/info.json
    - ../c_test/passwd.json
  hosts: "{{ hostname }}"
  gather_facts: false
  tasks:
    - name: "check if host is reachable"
      wait_for:
        timeout: 0
      register: connect_rs
      ignore_unreachable: yes
    
    - name: "try first login and change the pw"
      when: connect_rs is unreachable     
      delegate_to: "{{ host_ip }}"
      expert:        
        command: sshpass -p {{ ansible_first_login_password }} ssh {{ansible_ssh_common_args }} root@{{ host_ip  }}
        timeout: 10
        responses:
          Password: "{{ ansible_first_login_password }}"
          UNIX password: "{{ ansible_first_login_password }}"
          New password: "{{ ansible_password }}"
          new password: "{{ ansible_password }}"
    - name: "Gather facts about host"
      setup: