---
- name: change pw on initial login
  vars_files:
    - ../c_test/passwd.json
  delegate_to: "{{host_ip}}"
  become: no
  ansible.builtin.expect:
    command: ssh {{ ansible_ssh_common_args }} {{ user_expert }}@{{ host_ip  }}
    timeout: 20
    responses:
      Password: "{{ user_expert_password }}"
      UNIX password: "{{ user_expert_password }}"
      New password: "{{ user_expert_password_new }}"
      new password:  "{{ user_expert_password_new }}"
      "\\~\\]\\$": exit
  register: status
