---
- name: change pw on initial login
  vars_files:
    - ../c_test/passwd.json
  hosts: "{{ hostname }}"
  gather_facts: false
  tasks:
  - name: check if host is reachable
    wait_for:
      timeout: 0
    register: connect_rs
    ignore_unreachable: true
    when: ignore_unreachable == "true"
  - name: try first login and change the pw
    #delegate_to: "{{ host_ip }}"
    expect:        
      #command: sshpass -p {{ ansible_first_login_password }} ssh {{ansible_ssh_common_args }} root@{{ host_ip }}
      command: ssh root@{{ host_ip }}
      timeout: 10
      responses:
       "Password:": "{{ ansible_first_login_password }}"
       "Current password:": "{{ ansible_first_login_password }}"
       "New password:": "{{ ansible_password }}"
       "Retype new password:": "{{ ansible_password }}"
  - name: "Gather facts about host"
    setup: