---
- name: set dns
  vars_files:
    - ../vars/info.json
  hosts: "{{ hostname }}"
  tasks:
  - name: latest dnsmasq install
    yum: 
      name: dnsmasq
      state: latest
  - name: touch dns.conf
    command: touch /etc/dnsmasq.d/dns.conf 
  - name: change mode
    command: chmod 755 /etc/dnsmasq.d/dns.conf
  - name: set conf file 
    template: 
      src: ../template/dns_conf.j2
      dest: /etc/dnsmasq.d/dns.conf
  - name: start & enable dnsmasq
    service:
      name: dnsmasq
      state: started
      enabled: yes
  - name: start & enable dnsmasq
    service:
      name: dnsmasq
      state: restarted
      enabled: yes
  - name: check dnsmasq status
    command: systemctl status dnsmasq
    register: result
    ignore_errors: yes
  - name: show reoport
    debug:
      var: result 

  
    
    
