---
- name: set bastion hostname&firewalld&selinux
  hosts: "{{ hostname }}"
  tasks:
  - name: set-hostname
    shell: hostnamectl set-hostname bastion.ocp.{{ name }}.com > /etc/hostname
  - name: latest firewalld install
    yum:
      name: firewalld
      state: latest
  - name: stop disable firewalld
    service:
      name: firewalld
      state: stopped
      enabled: no
  - name: closed selinux
    shell: setenforce 0
  - name: disable forerver in config
    lineinfile:
      path: /etc/selinux/config
      regexp: SELINUX=enforcing
      line: 'SELINUX=permissive'