---
- name: Change password on initial login
  vars_files:
    - ../vars/info.json
  hosts: localhost2
  tasks:
    - name: connect ssh
      expect:
        command: ssh -o StrictHostKeyChecking=no root@{{ bastion_ip }}
        timeout: 20
        responses:
          "root@10.250.*.*": "changeme"
          "New password:": "Admin12345"
          "Retype new password:": "Admin12345"
          "\\~\\]\\$": exit
      register: status
