---
- name: reboot service
  hosts: "{{ hostname }}"
  tasks: 
   - name: reboot
     shell: "sleep 5 && reboot "
     async: 1
     poll: 0
   - name: wait for the reboot to complete if there was change
     wait_for_connection:
       connect_timeout: 10
       sleep: 5
       delay: 5
       timeout: 120
