---
- name: set resolv
  hosts: "{{ hostname }}"
  tasks:
  - name: change resolv.conf
    lineinfile:
      path: /etc/resolv.conf
      regexp: search dynakumo.local
      line: 'search ocp.{{ name }}.com'
  - name: change resolv
    lineinfile:
      path: /etc/resolv.conf
      insertafter: 'search ocp.{{ name }}.com'
      line: 'nameserver {{ dnsip }}'
  - name: forbid change
    command: chattr +i /etc/resolv.conf
