---
- name: generate ssh
  vars_files:
    - ../vars/info.json
  hosts: "{{ hostname }}"
  tasks: 
    - name: SSH keygen command
      shell: >
        ssh-keygen -t rsa -b 4096 -N "" -C "root@bastion.ocp.{{name}}.com" -f /root/.ssh/id_rsa
        creates="/root/.ssh/id_rsa"
    - name: Enable ssh agent & add key 
      shell: | 
        eval "$(ssh-agent -s)"
        ssh-add /root/.ssh/id_rsa
